---
title: "Unsere Übung"
subtitle: ""
date-format: long
format: 
    revealjs:
        theme: [serif]
        embed-resources: false
        slide-number: false
        chalkboard: true
        width: 1300
        preload-iframes: true
        # navigation-mode: grid
        preview-links: auto
        code-line-numbers: false
        auto-stretch: false
        # logo: "assets/logos/full-logo.png"
        include-in-header: 
            text: |
                <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Major+Mono+Display">
---

# Wörter

## 


| Nomen                                                       | Adjektive                                         | Verben                                   |
|-------------------------------------------------------------|--------------------------------------------------|-----------------------------------------|
| <span class="fragment" data-fragment-index="1">das Land / die Länder</span>             | <span class="fragment" data-fragment-index="1">reich</span>        | <span class="fragment" data-fragment-index="1">sein</span>         |
| <span class="fragment" data-fragment-index="1">die Tradition / die Traditionen</span>   |                                                  |                                         |
| <span class="fragment" data-fragment-index="1">die Kultur / die Kulturen</span>         |                                                  |                                         |
| <span class="fragment" data-fragment-index="2">die Musik </span>          |                                                  |                                         |
| <span class="fragment" data-fragment-index="2">die Kunst / die Künste</span>            |                                                  |                                         |
| <span class="fragment" data-fragment-index="2">das Fest / die Feste</span>              | <span class="fragment" data-fragment-index="2">wichtig</span>      |                                         |
: {tbl-colwidths="[50,25,25]"}



## 



| Nomen                                                       | Adjektive                                         | Verben                                   |
|-------------------------------------------------------------|--------------------------------------------------|-----------------------------------------|
| <span class="fragment" data-fragment-index="3">die Stadt / die Städte</span>            |                                                  | <span class="fragment" data-fragment-index="3">geben</span>        |
| <span class="fragment" data-fragment-index="3">das Museum / die Museen</span>           |                                                  |                                         |
| <span class="fragment" data-fragment-index="3">das Theater / die Theater</span>         |                                                  |                                         |
| <span class="fragment" data-fragment-index="3">das Konzert / die Konzerte</span>        |                                                  |                                         |
| <span class="fragment" data-fragment-index="4">die Tracht / die Trachten</span>         | <span class="fragment" data-fragment-index="4">regional</span>     | <span class="fragment" data-fragment-index="4">gehören</span>      |
| <span class="fragment" data-fragment-index="4">der Brauch / die Bräuche</span>          |                                                  |                                         |
| <span class="fragment" data-fragment-index="5">das Teil / die Teile</span>              |                                                  |                                         |
| <span class="fragment" data-fragment-index="5">das Zusammensein  </span> |                                                  |                                         |
: {tbl-colwidths="[50,25,25]"}


## 

| Nomen                                                       | Adjektive                                         | Verben                                   |
|-------------------------------------------------------------|--------------------------------------------------|-----------------------------------------|
| <span class="fragment" data-fragment-index="6">der Mensch / die Menschen</span>         | <span class="fragment" data-fragment-index="6">gern</span>         | <span class="fragment" data-fragment-index="6">sich treffen</span> |
| <span class="fragment" data-fragment-index="6">das Kaffeehaus / die Kaffeehäuser</span> |                                                  |                                         |
| <span class="fragment" data-fragment-index="7">die Familie / die Familien</span>        | <span class="fragment" data-fragment-index="7">groß</span>         | <span class="fragment" data-fragment-index="7">spielen</span>      |
| <span class="fragment" data-fragment-index="7">der Freund / die Freunde</span>          |                                                  |                                         |
| <span class="fragment" data-fragment-index="7">die Rolle / die Rollen</span>            |                                                  |                                         |
| <span class="fragment" data-fragment-index="8">das Essen </span>            | <span class="fragment" data-fragment-index="8">gut</span>          | <span class="fragment" data-fragment-index="8">haben</span>        |
| <span class="fragment" data-fragment-index="8">die Kleidung </span>    | <span class="fragment" data-fragment-index="8">traditionell</span> |                                         |
: {tbl-colwidths="[50,25,25]"}


## 

| Nomen                                                       | Adjektive                                         | Verben                                   |
|-------------------------------------------------------------|--------------------------------------------------|-----------------------------------------|
| <span class="fragment" data-fragment-index="9">die Arbeit / die Arbeiten</span>         | <span class="fragment" data-fragment-index="9">interessant</span>  |                                         |
| <span class="fragment" data-fragment-index="10">die Pünktlichkeit </span>            |                                                  |                                         |
| <span class="fragment" data-fragment-index="11">der Termin / die Termine</span>         | <span class="fragment" data-fragment-index="11">wirklich</span>    | <span class="fragment" data-fragment-index="11">beginnen</span>    |
|                                                             |                                                  | <span class="fragment" data-fragment-index="11">müssen</span>      |
|                                                             | <span class="fragment" data-fragment-index="12">höflich</span>     | <span class="fragment" data-fragment-index="12">sprechen</span>    |
|                                                             | <span class="fragment" data-fragment-index="12">respektvoll</span>|                                         |
: {tbl-colwidths="[50,25,25]"}


## 

| Nomen                                                       | Adjektive                                         | Verben                                   |
|-------------------------------------------------------------|--------------------------------------------------|-----------------------------------------|
| <span class="fragment" data-fragment-index="13">die Teamarbeit </span>               | <span class="fragment" data-fragment-index="13">klar</span>        |                                         |
| <span class="fragment" data-fragment-index="13">die Regel / die Regeln</span>           |                                                  |                                         |
| <span class="fragment" data-fragment-index="14">das Problem / die Probleme</span>       |                                                  |                                         |
| <span class="fragment" data-fragment-index="14">der Chef / die Chefs</span>             |                                                  |                                         |
| <span class="fragment" data-fragment-index="14">die Chefin / die Chefinnen</span>       |                                                  |                                         |
| <span class="fragment" data-fragment-index="15">die Firma / die Firmen</span>           |                                                  | <span class="fragment" data-fragment-index="15">unterstützen</span>|
| <span class="fragment" data-fragment-index="15">der Betriebsrat / die Betriebsräte</span>|                                                  |                                         |
| <span class="fragment" data-fragment-index="15">die Mitarbeiter:innen</span>            |                                                  |                                         |
: {tbl-colwidths="[50,25,25]"}



## 

| Nomen                                                       | Adjektive                                         | Verben                                   |
|-------------------------------------------------------------|--------------------------------------------------|-----------------------------------------|
| <span class="fragment" data-fragment-index="16">die Arbeitnehmer:innen</span>           |                                                  |                                         |
| <span class="fragment" data-fragment-index="16">das Recht / die Rechte</span>           |                                                  |                                         |
| <span class="fragment" data-fragment-index="16">der Urlaub / die Urlaube</span>         |                                                  |                                         |
| <span class="fragment" data-fragment-index="16">die Pause / die Pausen</span>           |                                                  |                                         |
| <span class="fragment" data-fragment-index="16">die Arbeitsbedingungen</span>           |                                                  |                                         |
: {tbl-colwidths="[50,25,25]"}




## 

Wir bauen Sätze mit auf:

::: {.incremental}

- gehören: Präsens, Frage
    - Welche Traditionen gehören zur Kultur in Österreich?
    - Die Kultur ist sehr reich. Dazu gehören die Musik, die Feste, die Kleidung und das Essen.

- sich treffen: Präsens, Frage
    - Die Menschen treffen sich immer bei den Festen.
    - Das Zusammensein ist sehr wichtig. Zum Beispiel treffen sich die Menschen in Kaffeehäusern.

:::


## 

Wir bauen Sätze mit auf:

::: {.incremental}

- spielen: Präsens
    - Die Musik, das Essen und die Kleidung spielen eine wichtige Rolle in der Kultur.
    - Die Pünktlichkeit spielt auch eine wichtige Rolle.

- beginnen: Präsens mit Modalverben
    - Die Termine sollen immer pünktlich beginnen.

- unterstützen: Präsens
    - Die Dienstbedingungen unterstützen immer die Arbeitnehmer:innen.
    - Die Eltern unterstützen ihre Kinder.

:::




##


:::: {.columns}

::: {.column}

::: {style="font-size: 45%"}


| Nomen                                 | Adjektive     | Verben          |
|---------------------------------------|---------------|-----------------|
| das Land / die Länder                  | reich         | sein            |
| die Tradition / die Traditionen        |               |                 |
| die Kultur / die Kulturen              |               |                 |
| die Musik                              |               |                 |
| die Kunst / die Künste                 |               |                 |
| das Fest / die Feste                   | wichtig       |                 |
| die Stadt / die Städte                 |               | geben           |
| das Museum / die Museen                |               |                 |
| das Theater / die Theater              |               |                 |
| das Konzert / die Konzerte             |               |                 |
| die Tracht / die Trachten              | regional      | gehören         |
| der Brauch / die Bräuche               |               |                 |
| das Teil / die Teile                   |               |                 |
| das Zusammensein                       |               |                 |
| der Mensch / die Menschen              | gern          | sich treffen    |
| das Kaffeehaus / die Kaffeehäuser      |               |                 |
| die Familie / die Familien             | groß          | spielen         |
| der Freund / die Freunde               |               |                 |
| die Rolle / die Rollen                 |               |                 |
| das Essen                              | gut           | haben           |
| die Kleidung                           | traditionell  |                 |

:::

:::


::: {.column}

::: {style="font-size: 45%"}


| Nomen                                 | Adjektive     | Verben          |
|---------------------------------------|---------------|-----------------|
| die Arbeit / die Arbeiten              | interessant   |                 |
| die Pünktlichkeit /                    |               |                 |
| der Termin / die Termine               | wirklich      | beginnen, müssen|
|                                        | höflich       | sprechen        |
|                                        | respektvoll   |                 |
| die Teamarbeit                         | klar          |                 |
| die Regel / die Regeln                 |               |                 |
| das Problem / die Probleme             |               |                 |
| der Chef / die Chefs                   |               |                 |
| die Chefin / die Chefinnen             |               |                 |
| die Firma / die Firmen                 |               | unterstützen    |
| der Betriebsrat / die Betriebsräte     |               |                 |
| der Mitarbeiter / die Mitarbeiter:innen|               |                 |
| der Arbeitnehmer / die Arbeitnehmer:innen|             |                 |
| das Recht / die Rechte                 |               |                 |
| der Urlaub / die Urlaube               |               |                 |
| die Pause / die Pausen                 |               |                 |
| die Arbeitsbedingung / -bedingungen    |               |                 |

:::

:::



::::